README.md

test build

---

README.md
sample-network/README.md

Amazon EKS configuration guidelines

---

README.md

Test PR 1 build at labs

---

Makefile

Signed-off-by: Ry Jones <ry@linux.com>

Push to right place

---

sample-network/network
sample-network/scripts/prereqs.sh

Bump fabric version to 2.4.4; CA to 1.5.4

---

pkg/offering/base/peer/peer.go
pkg/offering/base/peer/peer_test.go

Adding changes for auto-cert renewal

---

config/manager/manager.yaml

fix: selector and labels do not match

fix: selector and labels do not match

---

.github/workflows/unit-tests.yaml
Makefile
pkg/util/util.go

Fixing gosec issues

---

MAINTAINERS.md

Updating maintainers list to add and remove maintainers

---

.github/workflows/endtoend-tests.yaml
.github/workflows/unit-tests.yaml
pkg/offering/base/orderer/node.go
pkg/offering/base/orderer/node_test.go
pkg/offering/base/peer/override/deployment.go
pkg/util/util.go

https://github.com/hyperledger-labs/fabric-operator/issues/107

Orderer: adding auto-cert renewal functionality and port changes from master

---

sample-network-multi-org/config/configtx.yaml
sample-network-multi-org/config/core.yaml
sample-network-multi-org/config/orderer.yaml
sample-network-multi-org/scripts/kind_with_nginx.sh
sample-network-multi-org/scripts/test-e2e.sh

https://github.com/hyperledger-labs/fabric-operator/issues/109

Removed IBM Confidencial License

---

controllers/ibporderer/ibporderer_controller.go

https://github.com/hyperledger-labs/fabric-operator/issues/116

Donot update tls cert for 2.4.x -> 2.5.x osn upgrades

---

definitions/console/console-configmap.yaml
pkg/apis/console/v1/console.go

https://github.com/hyperledger-labs/fabric-operator/issues/124

Let console handle auth_scheme

---

defaultconfig/orderer/orderer.yaml
defaultconfig/orderer/v2/orderer.yaml
defaultconfig/orderer/v24/orderer.yaml
defaultconfig/orderer/v25/orderer.yaml
defaultconfig/peer/core.yaml
defaultconfig/peer/v2/core.yaml
defaultconfig/peer/v25/core.yaml
pkg/offering/base/orderer/override/deployment.go
pkg/offering/base/peer/override/deployment.go

https://github.com/hyperledger-labs/fabric-operator/issues/126

reduce keepalive interval to avoid connection issues on VPC

---

pkg/restart/staggerrestarts/staggerrestarts.go
pkg/restart/staggerrestarts/staggerrestarts_structs.go
pkg/restart/staggerrestarts/staggerrestarts_test.go

https://github.com/hyperledger-labs/fabric-operator/issues/128

Mark the item as deleted and remove from the Queue if deleted

---

.github/workflows/release.yaml

https://github.com/hyperledger-labs/fabric-operator/issues/114

Fix release build

---

defaultconfig/peer/v2/core.yaml
defaultconfig/peer/v25/core.yaml
pkg/offering/base/peer/override/deployment.go

https://github.com/hyperledger-labs/fabric-operator/issues/145

disable peer block gossiping with config blockGossipEnabled flag

---

pkg/offering/base/console/override/deployment.go

https://github.com/hyperledger-labs/fabric-operator/issues/148

Make use tags default to true for couchdb

---

pkg/initializer/common/config/hsmconfig.go
pkg/offering/base/ca/ca.go
pkg/offering/base/ca/ca_test.go
pkg/offering/base/ca/override/deployment_test.go
pkg/offering/base/orderer/node.go
pkg/offering/base/orderer/node_test.go
pkg/offering/base/orderer/override/deployment_test.go
pkg/offering/base/peer/override/deployment_test.go
pkg/offering/base/peer/peer.go

This PR addresses the renaming for the hsm configs

Updating hsm config name

---

.github/workflows/integration-tests.yaml
.github/workflows/release.yaml
.github/workflows/unit-tests.yaml
Dockerfile
Makefile
go.mod

https://github.com/hyperledger-labs/fabric-operator/issues/165

Bump golang version to 1.20 

---

definitions/ca/deployment.yaml
definitions/console/deployment.yaml
definitions/orderer/deployment.yaml
definitions/peer/chaincode-launcher.yaml
definitions/peer/couchdb.yaml
definitions/peer/deployment.yaml

Changes to disable read and write permissions to the group user

Fix Insecure File Permissions

---

defaultconfig/peer/v25/core.yaml

Add missing k8s_builder config to v25 core.yaml

---

.github/workflows/integration-tests.yaml
.github/workflows/release.yaml
.github/workflows/unit-tests.yaml
Makefile
go.mod

Bump go to 1.24.3

---

go.mod
go.sum

updated docker and grpc version

updated docker and grpc version
