hyperledger-labs/fabric-operator

sample-network/README.md, sample-network/config/core.yaml, sample-network/network, sample-network/scripts/chaincode.sh, sample-network/scripts/channel.sh
Add orderer timeout on chaincode calls.
Remove orderer flags on "peer channel join" since no connection to orderer is made.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>
=> Update Orderer --connTimeout

.github/workflows/endtoend-tests.yaml, config/ingress/k3s/kustomization.yaml, sample-network/README.md, sample-network/scripts/cluster.sh, sample-network/scripts/run-e2e-test.sh
This PR: 
- Switches to a CLUSTER-IP network interface for communication with the K8s Ingress
- Adds configuration notes for EKS and IKS clusters 
- Adds a `M.E.L.V.I.N.` ("Cousin of MARVIN") style end-to-end test, including chaincode deployments for `ccaas` and `k8s` executors on a scratch / disposable KIND cluster.
With the previous configuration, the network domain was based on the HOST OS interface to route traffic through the ingress controller.  This was _extremely confusing_, as the network IP varied widely from environment to environment.  With the new scheme, pods communicate with the ingress controller via the Kube INTERNAL (CLUSTER_IP) interface, which does not require a route back to the host OS.
The resulting configuration / README / guidelines are _tremendously simplified_, …
=> Switch from Host OS ingress to EXTERNAL-IP ingress for internal traffic - READY FOR MERGE

sample-network/network, sample-network/scripts/kind.sh
This PR bundles an insecure docker container registry at localhost:5000.  
During local build/edit/publish cycles for chaincode and gateway application development, the local registry can be used to publish docker images to k8s without uploading images to public / Internet-based registries. 
=> Bundle a localhost:5000 container registry for local CC development

sample-network/network
After installing the operator about 50 times in test clusters, I was wondering why the image download counts from ghcr.io were still zero.  This would explain the issue... 
Sample network now pulls the LABS operator image, not the legacy rev (pre-labs).
=> Use hyperledger-labs operator, not ibm-blockchain operator in sample network

definitions/orderer/deployment.yaml, definitions/peer/deployment.yaml
https://github.com/hyperledger-labs/fabric-operator/issues/59
=> Using port 8080 for proxy probe checks to fix the errors

sample-network/config/manager/hlf-operator-manager.yaml, sample-network/network, sample-network/scripts/kind.sh, sample-network/scripts/test_network.sh
This PR allows the sample network to run correctly (albeit, slowly) on the new Mac Silicon / arm64 chipset.
The docker images run as `linux/amd64` under QEMU, so performance is very slow.  We should improve the build pipeline to support the `buildx` builder and generate multi-arch containers. 
This PR addresses Issue #63 by pinning the KIND target revision to 1.24.4 (`KIND_CLUSTER_IMAGE`). 
=> Launch the sample network on Apple Silicon;  Pin k8s to 1.24

.github/workflows/integration-tests.yaml, .github/workflows/unit-tests.yaml, go.mod, go.sum
The recent ginkgo update requires golang 1.18.  This PR fixes the build pipeline, which was pinning the test version to 1.17. 
=> Fix the build: Run integration tests with golang 1.18, ginkgo v2.1.4, and gomega v1.19 

sample-network/scripts/test_network.sh
Stop service failed on `hlf console` due to typo in `sample-network/scripts/test_network.sh`
=> fix: console typo when stop sample network service

docs/DEVELOPING.md, main.go, pkg/command/operator.go
This PR allows the operator to be launched locally without running within a Docker container / kubernetes cluster.
Fixes Issue #67
Note that this changes the default path at which the operator config files are read, from `../../` to `./`.   This was actually a bug / error in the original logic, as the working directory for `ibp-operator` in the container is actually `/`.  (When running from the root folder, the `../../` path prefix resolves to `/` on the file system.)
Thank you @bjwswang for the great recommendations on pushing this forward.
=> Add an OPERATOR_LOCAL_MODE environment variable to launch locally.

integration/orderer/orderer_suite_test.go, pkg/offering/k8s/orderer/node.go, pkg/offering/openshift/orderer/node.go
the line87-89 and line 91-93 is same, but twice:
https://github.com/hyperledger-labs/fabric-operator/blob/db38e856fda7798650de925addadbc75305adc39/integration/orderer/orderer_suite_test.go#L85-L97
And line 205 and 206 is same but twice:
https://github.com/hyperledger-labs/fabric-operator/blob/db38e856fda7798650de925addadbc75305adc39/pkg/offering/k8s/orderer/node.go#L203-L210
=> chore: remove same code

scripts/go-sec.sh
gosec install script will auto get latest version(for example:https://github.com/bestchains/fabric-operator/actions/runs/3799271745/jobs/6461638960#step:5:7).  Not only is it unnecessary to get latest version, but this request is easily rejected by github, resulting in a `null` version (for example https://github.com/bestchains/fabric-operator/actions/runs/3799115622/jobs/6461341294#step:5:7) and installation failure.
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> fix: occasional gosec failure to get version

pkg/apis/ca/v1/ca.go, release_notes/v1.0.4-2.md
Adds support for Idemix configuration parameters to the CA CRD `spec.configoverride.ca.idemix` stanza.
=> Add support for CA Idemix config override stanza

.github/workflows/endtoend-tests.yaml
Close #102 
Close #104
#102 Shows a situation where the test failed but showed success.(This is not correct.)
#104 Shows that merge the current commit, the test fails and the display also fails.(This is correct.)
=> fix: E2E testing failed but displayed success

pkg/offering/base/ca/ca.go, pkg/offering/k8s/orderer/orderer.go, pkg/offering/k8s/peer/peer.go, pkg/offering/openshift/orderer/orderer.go, pkg/offering/openshift/peer/peer.go
https://github.com/hyperledger-labs/fabric-operator/issues/118
=> Include legacy dns in the tlscerts to fix post migration issues

go.mod, go.sum
As per https://nvd.nist.gov/vuln/detail/CVE-2022-36109
=> Upgrade to patched secure Docker version (no go mod tidy).

go.mod, go.sum
As per https://nvd.nist.gov/vuln/detail/CVE-2022-36109
=> Upgrade Docker to v20.10.18.

Makefile
https://github.com/hyperledger-labs/fabric-operator/issues/143
=> Fix the Makefile by adding missing targets

pkg/offering/base/orderer/override/deployment.go, pkg/offering/base/peer/override/deployment.go
https://github.com/hyperledger-labs/fabric-operator/issues/154
=> Change the probes from legacy endpoints to tcp ports

go.mod, go.sum
There was a major high vulnerability discovered in `github.com/docker/docker`, so, whether it is used for tests or actual production operation, we need to patch it in this project.
See https://nvd.nist.gov/vuln/detail/CVE-2023-28842
=> As per CVE-2023-28842 and others.

definitions/console/role.yaml
https://github.com/hyperledger-labs/fabric-operator/issues/177
In RBAC role definition for a console for app group, we have added resources as `- replicas` instead of `- replicasets`. Due to this replicasets are not accessible for the user with that RBAC.
=> console role definition replicasets resources typo correction

go.mod, go.sum
=> Move github.com/docker/docker to v24.0.9.

.github/workflows/endtoend-tests.yaml, .github/workflows/image-build-pr.yaml, .github/workflows/image-build.yaml, .github/workflows/integration-tests.yaml, .github/workflows/release.yaml, .github/workflows/unit-tests.yaml, Makefile, go.mod, go.sum
Bump Go to 1.21.11.
Note that starting with Go 1.21, the version in go.mod should be 3 digits.
=> Bump Go to 1.21.11

.github/workflows/integration-tests.yaml, .github/workflows/release.yaml, .github/workflows/unit-tests.yaml, Makefile, config/crd/bases/ibp.com_ibpcas.yaml, config/crd/bases/ibp.com_ibpconsoles.yaml, config/crd/bases/ibp.com_ibporderers.yaml, config/crd/bases/ibp.com_ibppeers.yaml, go.mod
Bump Go to 1.22.5.
Latest Go also requires an update to controller-gen (otherwise it panics with a nil pointer).
The controller-gen update in turn improves formatting of the generated CRD yaml files.
=> Bump Go to 1.22.5

go.mod, go.sum
updated dockerR to v26.1.5 as part of fix for CVE-2024-41110
=> fix for CVE-2024-41110

pkg/initializer/orderer/configtx/encoder.go
New versions of gosec implemented stricter type conversion and bounds checks. This conversion is not vulnerable so we can suppress the warning.
=> Fix gosec failures on integer conversion

go.mod, go.sum
Bump github.com/DataDog/zstd to v1.5.6.
=> Bump github.com/DataDog/zstd to v1.5.6
